# Settings

# Backup Setting
backup:
  download-path: D:\csdn-blog-backup  # Backup Path
  download-img: False # Backup Pictures ?

# CSDN Auth
user:
  username: your_username
  password: your_password


