# Settings

# Backup Setting
backup:
  download-path: D:\csdn-blog-backup  # Backup Path
  download-img: False # Backup Pictures ?
  sleep-time: 1 # Crawl article interval, default 1 seconds

# CSDN Auth
user:
  username: your_username
  password: your_password


